CREATE TABLE IF NOT EXISTS car(
    ID INT NOT NULL AUTO_INCREMENT,
    MODEL VARCHAR(50) NOT NULL,
    YEAR_OF_PRODUCTION DATE,
    NUMBER_OF_DOORS SMALLINT,
    GEARBOX VARCHAR(50),
    HORSE_POWER INT,
    MILLAGE INT,
    DETAILS TEXT,
    DATE_ADDED DATE,

    PRIMARY KEY(ID)
)Engine = INNODB;

CREATE TABLE IF NOT EXISTS rent(
    ID INT NOT NULL AUTO_INCREMENT,
    CAR_ID INT,
    RENT_PERIOD_START DATE NOT NULL,
    RENT_PERIOD_END DATE NOT NULL,
    BUSINESS_DAYS INT NOT NULL,
    TOTAL_RENT DECIMAL(9, 2) NOT NULL,
    CURRENCY VARCHAR(10) DEFAULT 'EURO',
    DATE_ADDED DATE,

    PRIMARY KEY(ID),
    FOREIGN KEY (CAR_ID)
        REFERENCES CAR(ID)
)Engine = INNODB;